### ISSUE TITLE
The container name "/jupyter-robnagler" is already in use by container

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsdockerspawner#12]
This cleared itself up with a "Relaunch" in the GUI, but still be good to understand.

```txt
ug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: return self.__get_result()
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: raise self._exception
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: result = self.fn(*self.args, **self.kwargs)
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 743, in _docker
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: return m(*args, **kwargs)
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/docker/api/container.py", line 429, in create_container
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: return self.create_container_from_config(config, name)
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/docker/api/container.py", line 440, in create_container_from_config
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: return self._result(res, True)
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: self._raise_for_status(response)
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: raise create_api_error_from_http_exception(e)
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: raise cls(e, response=response, explanation=explanation)
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/jupyter-robnagler" is already in use by container "613f5dcc818fa83db57c2ac385c524ad95c15742a94c09ef5118ad25ba37d2bf". You have to remove (or rename) that container to be able to reuse that name.")
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: ERROR:asyncio:Task exception was never retrieved
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=HTTPError()>
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: Traceback (most recent call last):
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: tornado.util.TimeoutError: Timeout
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: During handling of the above exception, another exception occurred:
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: Traceback (most recent call last):
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 922, in spawn_single_user
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: % (status, spawner._log_name),
Aug 20 23:17:57 fnl4b.bivio.biz jupyterhub[22189]: tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=0]. The logs for robnagler may contain details.)
```

**Comment by robnagler** [comment]
handled by other issues
